export const staffData = [
    {
        first_name: "John Doe",
        last_name: "John Doe",
        id: "CC101",
        dob: null,
        email: "john.doe@example.com",
        designation: "Barista",
        phone: "+1 123 456 7890",
        photo: "john_doe.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 12",
        joiningDate: "2023-01-15",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Jane Smith",
        last_name: "Jane Smith",
        id: "CC102",
        dob: 'dd-mm-yyyy',
        email: "jane.smith@example.com",
        designation: "Cashier",
        phone: "+1 234 567 8901",
        photo: "jane_smith.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 12",
        joiningDate: "2023-02-20",
        employmentStatus: "Part-time",
        gender: 'male'
    },
    {
        first_name: "Michael Johnson",
        last_name: "Michael Johnson",
        id: "CC103",
        dob: 'dd-mm-yyyy',
        email: "michael.johnson@example.com",
        designation: "Shift Supervisor",
        phone: "+1 345 678 9012",
        photo: "michael_johnson.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 2",
        joiningDate: "2022-12-10",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Emily Williams",
        last_name: "Emily Williams",
        id: "CC104",
        dob: 'dd-mm-yyyy',
        email: "emily.williams@example.com",
        designation: "Barista",
        phone: "+1 456 789 0123",
        photo: "emily_williams.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 2",
        joiningDate: "2023-03-05",
        employmentStatus: "Part-time",
        gender: 'male'
    },
    {
        first_name: "Robert Brown",
        last_name: "Robert Brown",
        id: "CC105",
        dob: 'dd-mm-yyyy',
        email: "robert.brown@example.com",
        designation: "Barista",
        phone: "+1 567 890 1234",
        photo: "robert_brown.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Uttara",
        joiningDate: "2023-04-12",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Olivia Jones",
        last_name: "Olivia Jones",
        id: "CC106",
        dob: 'dd-mm-yyyy',
        email: "olivia.jones@example.com",
        designation: "Cashier",
        phone: "+1 678 901 2345",
        photo: "olivia_jones.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Uttara",
        joiningDate: "2023-05-18",
        employmentStatus: "Part-time",
        gender: 'male'
    },
    {
        first_name: "William Miller",
        last_name: "William Miller",
        id: "CC107",
        dob: 'dd-mm-yyyy',
        email: "william.miller@example.com",
        designation: "Shift Supervisor",
        phone: "+1 789 012 3456",
        photo: "william_miller.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Basundhara",
        joiningDate: "2023-06-25",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Sophia Wilson",
        last_name: "Sophia Wilson",
        id: "CC108",
        dob: 'dd-mm-yyyy',
        email: "sophia.wilson@example.com",
        designation: "Barista",
        phone: "+1 890 123 4567",
        photo: "sophia_wilson.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Basundhara",
        joiningDate: "2023-07-30",
        employmentStatus: "Part-time",
        gender: 'male'
    },
    {
        first_name: "David Anderson",
        last_name: "David Anderson",
        id: "CC109",
        dob: 'dd-mm-yyyy',
        email: "david.anderson@example.com",
        designation: "Barista",
        phone: "+1 901 234 5678",
        photo: "david_anderson.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Banani",
        joiningDate: "2023-08-14",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    {
        first_name: "Emma Martinez",
        last_name: "Emma Martinez",
        id: "CC110",
        dob: 'dd-mm-yyyy',
        email: "emma.martinez@example.com",
        designation: "Cashier",
        phone: "+1 012 345 6789",
        photo: "emma_martinez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Banani",
        joiningDate: "2023-09-22",
        employmentStatus: "Part-time",
        gender: 'female'
    },
    {
        first_name: "Daniel Taylor",
        last_name: "Daniel Taylor",
        id: "CC111",
        dob: 'dd-mm-yyyy',
        email: "daniel.taylor@example.com",
        designation: "Shift Supervisor",
        phone: "+1 123 456 7890",
        photo: "daniel_taylor.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Gulshan-1",
        joiningDate: "2023-10-19",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    {
        first_name: "Isabella Garcia",
        last_name: "Isabella Garcia",
        id: "CC112",
        dob: 'dd-mm-yyyy',
        email: "isabella.garcia@example.com",
        designation: "Barista",
        phone: "+1 234 567 8901",
        photo: "isabella_garcia.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Gulshan-1",
        joiningDate: "2023-11-28",
        employmentStatus: "Part-time",
        gender: 'female'
    },
    {
        first_name: "James Rodriguez",
        last_name: "James Rodriguez",
        id: "CC113",
        dob: 'dd-mm-yyyy',
        email: "james.rodriguez@example.com",
        designation: "Barista",
        phone: "+1 345 678 9012",
        photo: "james_rodriguez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Khilgaon",
        joiningDate: "2023-12-07",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    {
        first_name: "Mia Lopez",
        last_name: "Mia Lopez",
        id: "CC114",
        dob: 'dd-mm-yyyy',
        email: "mia.lopez@example.com",
        designation: "Cashier",
        phone: "+1 456 789 0123",
        photo: "mia_lopez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Khilgaon",
        joiningDate: "2024-01-15",
        employmentStatus: "Part-time",
        gender: 'female'
    },
    {
        first_name: "Alexander Hernandez",
        last_name: "Alexander Hernandez",
        id: "CC115",
        dob: 'dd-mm-yyyy',
        email: "alexander.hernandez@example.com",
        designation: "Shift Supervisor",
        phone: "+1 567 890 1234",
        photo: "alexander_hernandez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Jhigatola",
        joiningDate: "2024-02-20",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    {
        first_name: "Sofia Perez",
        last_name: "Sofia Perez",
        id: "CC116",
        dob: 'dd-mm-yyyy',
        email: "sofia.perez@example.com",
        designation: "Barista",
        phone: "+1 678 901 2345",
        photo: "sofia_perez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Jhigatola",
        joiningDate: "2024-03-05",
        employmentStatus: "Part-time",
        gender: 'female'
    },
    {
        first_name: "Ethan Gonzalez",
        last_name: "Ethan Gonzalez",
        id: "CC117",
        dob: 'dd-mm-yyyy',
        email: "ethan.gonzalez@example.com",
        designation: "Barista",
        phone: "+1 789 012 3456",
        photo: "ethan_gonzalez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Dhanmondi 27", joiningDate: "2023-03-20",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "Alice Smith",
        last_name: "Alice Smith",
        id: "CC00124",
        dob: 'dd-mm-yyyy',
        email: "alice.smith@example.com",
        designation: "Cashier",
        phone: "+1987654321",
        photo: "alice_smith.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 2",
        joiningDate: "2023-03-20",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "Michael Johnson",
        last_name: "Michael Johnson",
        id: "CC00125",
        dob: 'dd-mm-yyyy',
        email: "michael.johnson@example.com",
        designation: "Shift Supervisor",
        phone: "+1122334455",
        photo: "michael_johnson.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Uttara",
        joiningDate: "2023-04-10",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "Emily Brown",
        last_name: "Emily Brown",
        id: "CC00126",
        dob: 'dd-mm-yyyy',
        email: "emily.brown@example.com",
        designation: "Chef",
        phone: "+14455667788",
        photo: "emily_brown.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Basundhara",
        joiningDate: "2023-05-05",
        employmentStatus: "Active",
        gender: 'female'
    },
    // Add more staff members here
    {
        first_name: "Robert Wilson",
        last_name: "Robert Wilson",
        id: "CC00127",
        dob: 'dd-mm-yyyy',
        email: "robert.wilson@example.com",
        designation: "Barista",
        phone: "+1567890123",
        photo: "robert_wilson.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Banani",
        joiningDate: "2023-06-15",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "Emma Davis",
        last_name: "Emma Davis",
        id: "CC00128",
        dob: 'dd-mm-yyyy',
        email: "emma.davis@example.com",
        designation: "Cashier",
        phone: "+1345678901",
        photo: "emma_davis.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Gulshan-1",
        joiningDate: "2023-07-20",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "James Martinez",
        last_name: "James Martinez",
        id: "CC00129",
        dob: 'dd-mm-yyyy',
        email: "james.martinez@example.com",
        designation: "Shift Supervisor",
        phone: "+1987123456",
        photo: "james_martinez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Khilgaon",
        joiningDate: "2023-08-10",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "Olivia Miller",
        last_name: "Olivia Miller",
        id: "CC00130",
        dob: 'dd-mm-yyyy',
        email: "olivia.miller@example.com",
        designation: "Chef",
        phone: "+1999888777",
        photo: "olivia_miller.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Jhigatola",
        joiningDate: "2023-09-05",
        employmentStatus: "Active",
        gender: 'female'
    },
    {
        first_name: "William Taylor",
        last_name: "William Taylor",
        id: "CC00131",
        dob: 'dd-mm-yyyy',
        email: "william.taylor@example.com",
        designation: "Barista",
        phone: "+1876543210",
        photo: "william_taylor.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Dhanmondi 27",
        joiningDate: "2023-10-15",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Sophia Anderson",
        last_name: "Sophia Anderson",
        id: "CC00132",
        dob: 'dd-mm-yyyy',
        email: "sophia.anderson@example.com",
        designation: "Cashier",
        phone: "+1765432109",
        photo: "sophia_anderson.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Chattogram",
        joiningDate: "2023-11-20",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Daniel Thomas",
        last_name: "Daniel Thomas",
        id: "CC00133",
        dob: 'dd-mm-yyyy',
        email: "daniel.thomas@example.com",
        designation: "Shift Supervisor",
        phone: "+1555666777",
        photo: "daniel_thomas.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 12",
        joiningDate: "2023-12-10",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Isabella Garcia",
        last_name: "Isabella Garcia",
        id: "CC00134",
        dob: 'dd-mm-yyyy',
        email: "isabella.garcia@example.com",
        designation: "Chef",
        phone: "+1223344556",
        photo: "isabella_garcia.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Mirpur 2",
        joiningDate: "2024-01-05",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "David Hernandez",
        last_name: "David Hernandez",
        id: "CC00135",
        dob: 'dd-mm-yyyy',
        email: "david.hernandez@example.com",
        designation: "Barista",
        phone: "+1888999777",
        photo: "david_hernandez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Uttara",
        joiningDate: "2024-02-15",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Mia Lopez",
        last_name: "Mia Lopez",
        id: "CC00136",
        dob: 'dd-mm-yyyy',
        email: "mia.lopez@example.com",
        designation: "Cashier",
        phone: "+1777888999",
        photo: "mia_lopez.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Basundhara",
        joiningDate: "2024-03-20",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Alexander King",
        last_name: "Alexander King",
        id: "CC00137",
        dob: 'dd-mm-yyyy',
        email: "alexander.king@example.com",
        designation: "Shift Supervisor",
        phone: "+1444333222",
        photo: "alexander_king.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Banani",
        joiningDate: "2024-04-10",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Sophie Scott",
        last_name: "Sophie Scott",
        id: "CC00138",
        dob: 'dd-mm-yyyy',
        email: "sophie.scott@example.com",
        designation: "Chef",
        phone: "+1888777666",
        photo: "sophie_scott.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Gulshan-1",
        joiningDate: "2024-05-05",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Ethan Green",
        last_name: "Ethan Green",
        id: "CC00139",
        dob: 'dd-mm-yyyy',
        email: "ethan.green@example.com",
        designation: "Barista",
        phone: "+1666555444",
        photo: "ethan_green.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Khilgaon",
        joiningDate: "2024-06-15",
        employmentStatus: "Active",
        gender: 'male'
    },
    {
        first_name: "Charlotte Hill",
        last_name: "Charlotte Hill",
        id: "CC00140",
        dob: 'dd-mm-yyyy',
        email: "charlotte.hill@example.com",
        designation: "Cashier",
        phone: "+1555666777",
        photo: "charlotte_hill.jpg",
        address: 'dhaka, Bangladesh',
        branchName: "Khilgaon",
        joiningDate: "2024-06-15",
        employmentStatus: "Active"
    },

    /* MAnagers */
    {
        first_name: "John",
        last_name: "Smith",
        id: "MG101",
        email: "john.smith@example.com",
        designation: "Manager",
        phone: "+1 123 456 7890",
        branchName: "Mirpur 12",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Jane",
        last_name: "Doe",
        id: "MG102",
        email: "jane.doe@example.com",
        designation: "Manager",
        phone: "+1 234 567 8901",
        branchName: "Mirpur 2",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    {
        first_name: "Michael",
        last_name: "Johnson",
        id: "MG103",
        email: "michael.johnson@example.com",
        designation: "Manager",
        phone: "+1 345 678 9012",
        branchName: "Uttara",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Emily",
        last_name: "Williams",
        id: "MG104",
        email: "emily.williams@example.com",
        designation: "Manager",
        phone: "+1 456 789 0123",
        branchName: "Basundhara",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    // Add more managers here
    {
        first_name: "Robert",
        last_name: "Brown",
        id: "MG105",
        email: "robert.brown@example.com",
        designation: "Manager",
        phone: "+1 567 890 1234",
        branchName: "Banani",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Olivia",
        last_name: "Jones",
        id: "MG106",
        email: "olivia.jones@example.com",
        designation: "Manager",
        phone: "+1 678 901 2345",
        branchName: "Gulshan-1",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    {
        first_name: "William",
        last_name: "Miller",
        id: "MG107",
        email: "william.miller@example.com",
        designation: "Manager",
        phone: "+1 789 012 3456",
        branchName: "Dhanmondi 27",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'male'
    },
    {
        first_name: "Sophia",
        last_name: "Wilson",
        id: "MG108",
        email: "sophia.wilson@example.com",
        designation: "Manager",
        phone: "+1 890 123 4567",
        branchName: "Chattogram",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'female'
    },
    // Super Manager
    {
        first_name: "Super",
        last_name: "Manager",
        id: "SM001",
        email: "super.manager@example.com",
        designation: "Super Manager",
        phone: "+1 999 999 9999",
        joiningDate: "2022-01-01",
        employmentStatus: "Full-time",
        gender: 'male'
    }
    /* Managers */
]

export const designations = [
    {
        "designation": "Barista",
        "description": "Responsible for preparing and serving coffee and other beverages, as well as maintaining cleanliness and customer service."
    },
    {
        "designation": "Cashier",
        "description": "Responsible for handling transactions, processing payments, and providing customer service at the counter."
    },
    {
        "designation": "Shift Supervisor",
        "description": "Responsible for overseeing daily operations, managing staff, handling customer inquiries, and ensuring smooth workflow during shifts."
    },
    {
        "designation": "Chef",
        "description": "Responsible for preparing and cooking food items, maintaining kitchen cleanliness, and ensuring food quality and safety."
    },
    {
        "designation": "Manager",
        "description": "Responsible for overall management of the branch, including staff supervision, inventory management, customer satisfaction, and operational efficiency."
    },
    {
        "designation": "Super Manager",
        "description": "Responsible for overseeing multiple branches, setting company policies, ensuring consistency across branches, and strategic decision-making."
    }
]